server:
  port: 6000
  context-path: /sso2

security:
  oauth2:
    client:
      client-id: client2
      client-secret: 123456
      user-authorization-uri: http://localhost:9000/auth/oauth/authorize
      access-token-uri: http://localhost:9000/auth/oauth/token
      scope: write
      authorized-grant-types: authorization_code
    resource:
      user-info-uri: http://localhost:9000/auth/oauth/check_token